### ISSUE TITLE
support for additional Raw type -> Sony .ARW

### ISSUE THREAD

**Issue by DC9VQ** [makoni/jpg-to-heif-converter#10]
it would be great iy you could add the support for the Sony raw files. Currently I'm working with a canon and Sony and I'm missing the convert functions for my Sony.

**Comment by makoni** [comment]
Hi @Leon191919 

Added support for .SR2 and .ARW files. Try new version: https://github.com/makoni/jpg-to-heif-converter/releases/tag/1.06
