### ISSUE TITLE
Question: default quality settings before 1.06?

### ISSUE THREAD

**Issue by SolaWeng** [makoni/jpg-to-heif-converter#16]
The new 1.07 version gives option to set output quality. Just curious, what is the default quality before this version?

**Comment by makoni** [comment]
Apple doesn't mention default value but I found that tweet:
https://twitter.com/tgaul/status/1184921487129530368

So probably by default it was 0.75

**Comment by SolaWeng** [comment]
awesome! Thanks for clarification. I did some test myself and it seems to produce similar file size when the quality is set to 0.8-0.85. So 0.75 totally makes sense to me.
