### ISSUE TITLE
RAW to HEIF conversion support

### ISSUE THREAD

**Issue by mrowlinson** [makoni/jpg-to-heif-converter#2]
Would you consider adding support for RAW files? Believe it or not yours is the only HEIF converter out there that will batch convert images so as it is now to convert my RAW files I have to open them one by one and manually export to HEIF. Supporting RAW would substantially reduce the amount of time I have to spend converting my RAW files.

Thanks for your work on this application!

**Comment by desolator7** [comment]
It seems the function used in this application already supports RAW files. 
It compresses my Nikon NEF RAW files with 10MB down to 600KB with all GPS and EXIF data, and without noticable loss, nice!

I only edited 1 line
`panel.allowedFileTypes = ["jpg", "jpeg", "png", "nef"]`

**Comment by mrowlinson** [comment]
Wow awesome! I guess it must be using Core Image to do the image processing. Hopefully the creator can update it to enable the other file extensions. Nikon NEF is what I need as well. Any chance you could throw your updated version enabling it on Dropbox or something so I can use it until the official version is updated?

**Comment by makoni** [comment]
@desolator7 thanks for advice!

Support for RAW files (NEF and CR2) added in [version 1.03](https://github.com/makoni/jpg-to-heif-converter/releases/tag/1.03) :)

**Comment by wojtekmaj** [comment]
Hi! Any chance for support of RW2 files, too?
